# frozen_string_literal: true

source "https://rubygems.org"

gem 'calabash-android'
gem 'cucumber'
gem 'rubyzip', '1.2.1' # Required version for running calabash-android in Windows
gem 'kraken-mobile', path: './vendor/KrakenMobile-1.0.9'
