# frozen_string_literal: true

source "https://rubygems.org"

gem 'calabash-android'
gem 'cucumber'
gem 'rubyzip', '1.2.1' # Required version for running calabash-android in Windows
gem 'kraken-mobile', git: 'https://github.com/cgarciasantander/KrakenMobile.git', tag: '1.0.10'
