version: '3.4'

networks:
  ghost_dev:
    name: ghost_dev
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
services:
  ghost:
    container_name: ghost
    image: ghost-test
    build:
      context: .
      dockerfile: ./Dockerfile-ghost
    environment:
      spam__user_login__freeRetries: 1000
      url: http://172.26.0.1:2368
      NODE_ENV: development
    ports:
      - 2368:2368
    networks:
      - ghost_dev

  cypress:
    container_name: cypress-chrome
    depends_on: 
      - ghost
    image: cypress/included:7.2.0
    environment:
      CYPRESS_baseUrl: http://172.26.0.1:2368
      CYPRESS_GHOST_USER: user@test.com
      CYPRESS_GHOST_PASS: dev1234567
    working_dir: /e2e
    volumes:
      - ./cypress-ghost:/e2e

  kraken-web:
    container_name: kraken-web
    image: kraken-web
    build:
      context: .
      dockerfile: ./Dockerfile-kraken
    environment:
      GHOST_URL: http://172.26.0.1:2368
      GHOST_USER: user@test.com
      GHOST_PASS: dev1234567
    depends_on: 
      - ghost
    volumes: 
      - ./kraken-ghost:/app
    networks:
      - ghost_dev
