LABEL Name=VRT-Report Version=0.0.1

# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /VTR-Code/VRT-4103

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "VRT-4103.exe"]

#Ubuntu 64
# copy and publish app and libraries
#COPY . .
#RUN dotnet publish -c release -o /app -r linux-x64 --self-contained false --no-restore

# final stage/image
#FROM mcr.microsoft.com/dotnet/runtime:5.0-focal-amd64
#WORKDIR /app
#COPY --from=build /app .
#ENTRYPOINT ["./dotnetapp"]