FROM runmymind/docker-android-sdk:ubuntu-standalone

LABEL Name=kraken-web Version=0.0.1

EXPOSE 3000
EXPOSE 9222

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install build-essential -y && \
    apt-get install chromium-chromedriver -y && \ 
    apt-get install ruby-dev -y

ENV PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

RUN gem install bundler -v 2.2.17

# throw errors if Gemfile has been modified since Gemfile.lock
# RUN bundle config --global frozen 1

WORKDIR /app
COPY ./kraken-ghost /app

RUN bundle install

ENV BROWSER=chrome

CMD make test