# Contents of Gemfile
source "https://rubygems.org"
gem 'rexml'
gem 'rubyzip', '1.2.1' # Required version for running calabash-android in Windows
gem 'kraken-mobile', path: '../../KrakenMobile-1.0.9'

